name: Maven Build with JFrog Fly

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup JFrog Fly
      uses: jfrog/fly-action@v1
      with:
        url: https://jfmarketing.jfrog.io
        
    - name: Build with Maven
      run: mvn clean install -B
      
    - name: Run tests
      run: mvn test
      
    - name: Package artifacts
      run: mvn package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: |
          **/target/*.jar
          **/target/*.war
        retention-days: 30

