name: Maven Example Build with JFrog Fly

on:
  push:
    branches: [ main, master ]
    paths:
      - 'maven-examples/maven-example/**'
      - '.github/workflows/maven-example-build.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'maven-examples/maven-example/**'
      - '.github/workflows/maven-example-build.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: maven-examples/maven-example
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup JFrog Fly
      uses: jfrog/fly-action@v1
      with:
        url: https://jfmarketing.jfrog.io
        
    - name: Build with Maven
      run: mvn clean install -B
      
    - name: Run tests
      run: mvn test
      
    - name: Package artifacts
      run: mvn package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: |
          maven-examples/maven-example/**/target/*.jar
          maven-examples/maven-example/**/target/*.war
        retention-days: 30

